// flow-typed signature: eed5223d73bc0c8633f25b964638b00a
// flow-typed version: <<STUB>>/mori_v0.3.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mori'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mori' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mori/bench/mut_perf' {
  declare module.exports: any;
}

declare module 'mori/bench/proxy_vs_freeze' {
  declare module.exports: any;
}

declare module 'mori/bench/transducers' {
  declare module.exports: any;
}

declare module 'mori/bench/trie_perf' {
  declare module.exports: any;
}

declare module 'mori/docs/js/shAutoloader' {
  declare module.exports: any;
}

declare module 'mori/docs/js/shBrushClojure' {
  declare module.exports: any;
}

declare module 'mori/docs/js/shBrushJScript' {
  declare module.exports: any;
}

declare module 'mori/docs/js/shCore' {
  declare module.exports: any;
}

declare module 'mori/docs/js/xregexp-min' {
  declare module.exports: any;
}

declare module 'mori/mori' {
  declare module.exports: any;
}

declare module 'mori/out-mori-adv/cljs/core' {
  declare module.exports: any;
}

declare module 'mori/out-mori-adv/clojure/set' {
  declare module.exports: any;
}

declare module 'mori/out-mori-adv/constants_table' {
  declare module.exports: any;
}

declare module 'mori/out-mori-adv/mori' {
  declare module.exports: any;
}

declare module 'mori/out-mori-adv/mori/mutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mori/bench/mut_perf.js' {
  declare module.exports: $Exports<'mori/bench/mut_perf'>;
}
declare module 'mori/bench/proxy_vs_freeze.js' {
  declare module.exports: $Exports<'mori/bench/proxy_vs_freeze'>;
}
declare module 'mori/bench/transducers.js' {
  declare module.exports: $Exports<'mori/bench/transducers'>;
}
declare module 'mori/bench/trie_perf.js' {
  declare module.exports: $Exports<'mori/bench/trie_perf'>;
}
declare module 'mori/docs/js/shAutoloader.js' {
  declare module.exports: $Exports<'mori/docs/js/shAutoloader'>;
}
declare module 'mori/docs/js/shBrushClojure.js' {
  declare module.exports: $Exports<'mori/docs/js/shBrushClojure'>;
}
declare module 'mori/docs/js/shBrushJScript.js' {
  declare module.exports: $Exports<'mori/docs/js/shBrushJScript'>;
}
declare module 'mori/docs/js/shCore.js' {
  declare module.exports: $Exports<'mori/docs/js/shCore'>;
}
declare module 'mori/docs/js/xregexp-min.js' {
  declare module.exports: $Exports<'mori/docs/js/xregexp-min'>;
}
declare module 'mori/mori.js' {
  declare module.exports: $Exports<'mori/mori'>;
}
declare module 'mori/out-mori-adv/cljs/core.js' {
  declare module.exports: $Exports<'mori/out-mori-adv/cljs/core'>;
}
declare module 'mori/out-mori-adv/clojure/set.js' {
  declare module.exports: $Exports<'mori/out-mori-adv/clojure/set'>;
}
declare module 'mori/out-mori-adv/constants_table.js' {
  declare module.exports: $Exports<'mori/out-mori-adv/constants_table'>;
}
declare module 'mori/out-mori-adv/mori.js' {
  declare module.exports: $Exports<'mori/out-mori-adv/mori'>;
}
declare module 'mori/out-mori-adv/mori/mutable.js' {
  declare module.exports: $Exports<'mori/out-mori-adv/mori/mutable'>;
}
